local gs = require('gitsigns')
gs.setup()
-- the :w is so fugitive will pick up the staging changes
vim.keymap.set('n', '<leader>gs', gs.stage_hunk)
vim.keymap.set('v', '<leader>gs', function() gs.stage_hunk {vim.fn.line("."), vim.fn.line("v")} end)
vim.keymap.set('n', '<leader>gr', gs.reset_hunk)
vim.keymap.set('v', '<leader>gr', function() gs.reset_hunk {vim.fn.line("."), vim.fn.line("v")} end)
vim.keymap.set('n', '<leader>gu', gs.undo_stage_hunk)
vim.keymap.set('n', '<leader>gR', gs.reset_buffer)
vim.keymap.set('n', '<leader>gS', gs.stage_buffer)
vim.keymap.set('n', '<leader>gn', gs.next_hunk)
vim.keymap.set('n', '<leader>gp', gs.prev_hunk)
vim.keymap.set('n', '<leader>gP', gs.preview_hunk)
vim.keymap.set('n', '<leader>gb', function() gs.blame_line{full=true} end)
vim.keymap.set('n', '<leader>gB', gs.toggle_current_line_blame)
vim.keymap.set('n', '<leader>gU', gs.reset_buffer_index)
vim.keymap.set('n', '<leader>gq', gs.setqflist)
vim.keymap.set('n', '<leader>gd', gs.diffthis)
